run:
	@g++ -o main main.cpp \
		./source/computing_machine.cpp \
		./source/laptop.cpp \
		./source/monoblock.cpp \
		./source/personal_computer.cpp \
		./source/portable_machine.cpp \
		./source/smart_phone.cpp \
		../string/string.cpp \
		./source/menu.cpp \
		./source/input_utils.cpp \

	./main 