run:
	@g++ -o main main.cpp \
		./source/computing_machine.cpp \
		./source/laptop.cpp \
		./source/monoblock.cpp \
		./source/personal_computer.cpp \
		./source/portable_machine.cpp \
		./source/smart_phone.cpp \
		./source/device_menu.cpp \
		../string/string.cpp

	./main